export const availableTags: { label: string; value: string }[] = [
  { label: 'Angular', value: 'angular' },
  { label: 'React', value: 'react' },
  { label: 'Vue', value: 'vue' },
  { label: 'TypeScript', value: 'typescript' },
  { label: 'JavaScript', value: 'javascript' },
  { label: 'Node.js', value: 'nodejs' },
  { label: 'Express', value: 'express' },
  { label: 'NestJS', value: 'nestjs' },
  { label: 'PrimeNG', value: 'primeng' },
  { label: 'Bootstrap', value: 'bootstrap' },
  { label: 'Tailwind CSS', value: 'tailwind' },
  { label: 'SASS', value: 'sass' },
  { label: 'Web Development', value: 'webdev' },
  { label: 'Frontend', value: 'frontend' },
  { label: 'Backend', value: 'backend' },
  { label: 'Fullstack', value: 'fullstack' },
  { label: 'API', value: 'api' },
  { label: 'REST', value: 'rest' },
  { label: 'GraphQL', value: 'graphql' },
  { label: 'Database', value: 'database' },
  { label: 'MongoDB', value: 'mongodb' },
  { label: 'PostgreSQL', value: 'postgresql' },
  { label: 'MySQL', value: 'mysql' },
  { label: 'Docker', value: 'docker' },
  { label: 'Kubernetes', value: 'kubernetes' },
  { label: 'AWS', value: 'aws' },
  { label: 'Azure', value: 'azure' },
  { label: 'Firebase', value: 'firebase' },
  { label: 'Testing', value: 'testing' },
  { label: 'Jest', value: 'jest' },
  { label: 'Cypress', value: 'cypress' },
  { label: 'CI/CD', value: 'cicd' },
  { label: 'Git', value: 'git' },
  { label: 'GitHub', value: 'github' },
  { label: 'GitLab', value: 'gitlab' },
  { label: 'DevOps', value: 'devops' },
  { label: 'Microservices', value: 'microservices' },
  { label: 'Authentication', value: 'auth' },
  { label: 'JWT', value: 'jwt' },
  { label: 'OAuth', value: 'oauth' },
  { label: 'Security', value: 'security' },
  { label: 'Performance', value: 'performance' },
  { label: 'SEO', value: 'seo' },
  { label: 'Mobile', value: 'mobile' },
  { label: 'Responsive Design', value: 'responsive' },
  { label: 'UI/UX', value: 'uiux' },
];
